"""create table headers

Revision ID: 137af1a08ce9
Revises: 98bf454f61f6
Create Date: 2026-03-23 19:49:44.446220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '137af1a08ce9'
down_revision: Union[str, Sequence[str], None] = '98bf454f61f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_headers',
    sa.Column('table_header_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('table_header_id'),
    sa.UniqueConstraint('table_name', 'column_name', name='uq_table_column')
    )
    op.create_index('idx_table_columns_table_name', 'table_headers', ['table_name'], unique=False, postgresql_where='is_visible = TRUE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_table_columns_table_name', table_name='table_headers', postgresql_where='is_visible = TRUE')
    op.drop_table('table_headers')
    # ### end Alembic commands ###
