"""create sam_data table

Revision ID: 2aa5f4c6a410
Revises: b88f346ae5fe
Create Date: 2026-03-20 18:00:51.942220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2aa5f4c6a410'
down_revision: Union[str, Sequence[str], None] = 'b88f346ae5fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sam_data',
    sa.Column('sam_data_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extracted_type', sa.String(length=10), nullable=False),
    sa.Column('extracted_by', sa.UUID(), nullable=False),
    sa.Column('C1', sa.String(length=50), nullable=True),
    sa.Column('C2', sa.String(length=120), nullable=True),
    sa.Column('C3', sa.String(length=100), nullable=True),
    sa.Column('C4', sa.String(length=100), nullable=True),
    sa.Column('C5', sa.String(length=20), nullable=True),
    sa.Column('C6', sa.String(length=40), nullable=True),
    sa.Column('C7', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C8', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C9', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C10', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C11', sa.Integer(), nullable=True),
    sa.Column('C12', sa.Integer(), nullable=True),
    sa.Column('C13', sa.Integer(), nullable=True),
    sa.CheckConstraint("extracted_type IN('admin', 'user')", name='check_extracted_type'),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sam_data_id')
    )
    op.create_index('idx_extracted_at', 'sam_data', ['extracted_at'], unique=False)
    op.create_index('idx_sam_data_file', 'sam_data', ['file_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sam_data_file', table_name='sam_data')
    op.drop_index('idx_extracted_at', table_name='sam_data')
    op.drop_table('sam_data')
    # ### end Alembic commands ###
