"""sam_data table updating

Revision ID: 33a9a1e2f52c
Revises: 8f3d1a86458a
Create Date: 2026-03-26 19:50:05.895852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a9a1e2f52c'
down_revision: Union[str, Sequence[str], None] = '8f3d1a86458a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sam_data', 'file_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sam_data', 'extracted_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('sam_data', 'extracted_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sam_data', 'extracted_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sam_data', 'extracted_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('sam_data', 'file_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
