"""all db tables

Revision ID: 3716b7d5c166
Revises: 98bf454f61f6
Create Date: 2026-03-23 13:38:43.149616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3716b7d5c166'
down_revision: Union[str, Sequence[str], None] = '98bf454f61f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_events',
    sa.Column('auth_event_id', sa.UUID(), nullable=False),
    sa.Column('app_user_type', sa.String(length=10), nullable=False),
    sa.Column('app_user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('happened_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('related_event_id', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('auth_event_id')
    )
    op.create_index('idx_auth_events_app_user_id', 'auth_events', ['app_user_id'], unique=False)
    op.create_index('idx_auth_events_app_user_type', 'auth_events', ['app_user_type'], unique=False)
    op.create_index('idx_auth_events_happened_at', 'auth_events', ['happened_at'], unique=False)
    op.create_index('idx_auth_events_type', 'auth_events', ['event_type'], unique=False)
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('file_version', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_month_year', sa.Integer(), nullable=False),
    sa.Column('processor_type', sa.String(length=10), nullable=False),
    sa.Column('processor_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('file_month_year >= 12000 AND file_month_year <= 122099', name='chk_file_month_year_range'),
    sa.PrimaryKeyConstraint('file_id'),
    sa.UniqueConstraint('file_name', 'file_month_year', name='unique_file_name_month_year')
    )
    op.create_index('idx_downloads_file', 'files', ['file_id'], unique=False)
    op.create_index('idx_files_month_year', 'files', ['file_month_year'], unique=False)
    op.create_index('idx_files_processor', 'files', ['processor_type', 'processor_id'], unique=False)
    op.create_index('idx_processed_time', 'files', ['processed_at'], unique=False)
    op.create_table('sam_data',
    sa.Column('sam_data_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extractor_type', sa.String(length=10), nullable=False),
    sa.Column('extracted_by', sa.UUID(), nullable=False),
    sa.Column('C1', sa.String(length=50), nullable=True),
    sa.Column('C2', sa.String(length=120), nullable=True),
    sa.Column('C3', sa.String(length=100), nullable=True),
    sa.Column('C4', sa.String(length=100), nullable=True),
    sa.Column('C5', sa.String(length=20), nullable=True),
    sa.Column('C6', sa.String(length=40), nullable=True),
    sa.Column('C7', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C8', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C9', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C10', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C11', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('C12', sa.Integer(), nullable=True),
    sa.Column('C13', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sam_data_id')
    )
    op.create_index('idx_extracted_extracted_at', 'sam_data', ['extracted_at'], unique=False)
    op.create_index('idx_extracted_file', 'sam_data', ['file_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_admin_id', sa.UUID(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.admin_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_users_created_by', 'users', ['created_by_admin_id'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_created_by', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_extracted_file', table_name='sam_data')
    op.drop_index('idx_extracted_extracted_at', table_name='sam_data')
    op.drop_table('sam_data')
    op.drop_index('idx_processed_time', table_name='files')
    op.drop_index('idx_files_processor', table_name='files')
    op.drop_index('idx_files_month_year', table_name='files')
    op.drop_index('idx_downloads_file', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_auth_events_type', table_name='auth_events')
    op.drop_index('idx_auth_events_happened_at', table_name='auth_events')
    op.drop_index('idx_auth_events_app_user_type', table_name='auth_events')
    op.drop_index('idx_auth_events_app_user_id', table_name='auth_events')
    op.drop_table('auth_events')
    # ### end Alembic commands ###
