"""create table headers

Revision ID: 96c46ece6a7e
Revises: 9ece15e77f7b
Create Date: 2026-03-25 21:27:21.908933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96c46ece6a7e'
down_revision: Union[str, Sequence[str], None] = '9ece15e77f7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- 1. Ensure UUID generation is available ---
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')

    # --- 2. Add new columns safely (nullable first) ---
    op.add_column(
        'table_headers',
        sa.Column('columns_schema', sa.JSON(), nullable=True)
    )
    op.add_column(
        'table_headers',
        sa.Column('is_active', sa.Boolean(), nullable=True)
    )
    op.add_column(
        'table_headers',
        sa.Column(
            'create_datetime',
            sa.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=True
        )
    )
    op.add_column(
        'table_headers',
        sa.Column(
            'update_datetime',
            sa.TIMESTAMP(),
            server_default=sa.text('now()'),
            nullable=True
        )
    )

    # --- 3. Populate existing rows ---
    op.execute(
        "UPDATE table_headers SET columns_schema = '{}' WHERE columns_schema IS NULL"
    )
    op.execute(
        "UPDATE table_headers SET is_active = true WHERE is_active IS NULL"
    )

    # --- 4. Enforce NOT NULL ---
    op.alter_column('table_headers', 'columns_schema', nullable=False)
    op.alter_column('table_headers', 'is_active', nullable=False)

    # --- 5. Migrate INTEGER → UUID safely ---
    op.add_column(
        'table_headers',
        sa.Column('new_table_header_id', sa.UUID(), nullable=True)
    )

    # Generate UUIDs
    op.execute(
        "UPDATE table_headers SET new_table_header_id = gen_random_uuid()"
    )

    # Make NOT NULL
    op.alter_column('table_headers', 'new_table_header_id', nullable=False)

    # Drop old PK column
    op.drop_column('table_headers', 'table_header_id')

    # Rename new column
    op.alter_column(
        'table_headers',
        'new_table_header_id',
        new_column_name='table_header_id'
    )

    # --- 6. Drop old constraints/indexes ---
    op.drop_index(
        op.f('idx_table_columns_table_name'),
        table_name='table_headers',
        postgresql_where='(is_visible = true)'
    )
    op.drop_constraint(
        op.f('uq_table_column'),
        'table_headers',
        type_='unique'
    )

    # --- 7. Drop old columns ---
    op.drop_column('table_headers', 'column_name')
    op.drop_column('table_headers', 'is_visible')
    op.drop_column('table_headers', 'order')
    op.drop_column('table_headers', 'display_name')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_headers', sa.Column('display_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
    op.add_column('table_headers', sa.Column('order', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.add_column('table_headers', sa.Column('is_visible', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('table_headers', sa.Column('column_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_table_column'), 'table_headers', ['table_name', 'column_name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_table_columns_table_name'), 'table_headers', ['table_name'], unique=False, postgresql_where='(is_visible = true)')
    op.alter_column('table_headers', 'table_header_id',
               existing_type=sa.UUID(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('table_headers', 'update_datetime')
    op.drop_column('table_headers', 'create_datetime')
    op.drop_column('table_headers', 'is_active')
    op.drop_column('table_headers', 'columns_schema')
    # ### end Alembic commands ###
