"""Updated sam data table

Revision ID: 9ece15e77f7b
Revises: ff35aa3cda9c
Create Date: 2026-03-25 18:46:13.168534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ece15e77f7b'
down_revision: Union[str, Sequence[str], None] = 'ff35aa3cda9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_headers',
    sa.Column('table_header_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('table_header_id'),
    sa.UniqueConstraint('table_name', 'column_name', name='uq_table_column')
    )
    op.create_index('idx_table_columns_table_name', 'table_headers', ['table_name'], unique=False, postgresql_where='is_visible = TRUE')
    op.add_column('sam_data', sa.Column('extracted_type', sa.String(length=10), nullable=False))
    op.add_column('sam_data', sa.Column('record_id', sa.String(length=50), nullable=False))
    op.add_column('sam_data', sa.Column('duns_number', sa.String(length=50), nullable=True))
    op.add_column('sam_data', sa.Column('status_code', sa.String(length=10), nullable=True))
    op.add_column('sam_data', sa.Column('entity_type', sa.String(length=10), nullable=True))
    op.add_column('sam_data', sa.Column('registration_date', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('expiration_date', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('last_update_date', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('activation_date', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('organization_name', sa.String(length=255), nullable=False))
    op.add_column('sam_data', sa.Column('legal_business_name', sa.String(length=255), nullable=True))
    op.add_column('sam_data', sa.Column('division_name', sa.String(length=255), nullable=True))
    op.add_column('sam_data', sa.Column('address_line1', sa.String(length=255), nullable=True))
    op.add_column('sam_data', sa.Column('address_line2', sa.String(length=255), nullable=True))
    op.add_column('sam_data', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('sam_data', sa.Column('state', sa.String(length=50), nullable=True))
    op.add_column('sam_data', sa.Column('zip_code', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('zip_extension', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('country', sa.String(length=50), nullable=True))
    op.add_column('sam_data', sa.Column('congressional_district', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('business_start_date', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('fiscal_year_end', sa.String(length=20), nullable=True))
    op.add_column('sam_data', sa.Column('website', sa.String(length=255), nullable=True))
    op.drop_index(op.f('idx_extracted_extracted_at'), table_name='sam_data')
    op.drop_index(op.f('idx_extracted_file'), table_name='sam_data')
    op.create_index('idx_extracted_at', 'sam_data', ['extracted_at'], unique=False)
    op.create_index('idx_org_name', 'sam_data', ['organization_name'], unique=False)
    op.create_index('idx_sam_data_file', 'sam_data', ['file_id'], unique=False)
    op.create_index('idx_state', 'sam_data', ['state'], unique=False)
    op.drop_column('sam_data', 'C9')
    op.drop_column('sam_data', 'C12')
    op.drop_column('sam_data', 'C6')
    op.drop_column('sam_data', 'C4')
    op.drop_column('sam_data', 'C3')
    op.drop_column('sam_data', 'C10')
    op.drop_column('sam_data', 'C5')
    op.drop_column('sam_data', 'C7')
    op.drop_column('sam_data', 'C8')
    op.drop_column('sam_data', 'C2')
    op.drop_column('sam_data', 'C1')
    op.drop_column('sam_data', 'C11')
    op.drop_column('sam_data', 'extractor_type')
    op.drop_column('sam_data', 'C13')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sam_data', sa.Column('C13', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('extractor_type', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('sam_data', sa.Column('C11', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C1', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C2', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C8', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C7', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C5', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C10', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C3', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C4', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C6', sa.VARCHAR(length=40), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C12', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('sam_data', sa.Column('C9', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
    op.drop_index('idx_state', table_name='sam_data')
    op.drop_index('idx_sam_data_file', table_name='sam_data')
    op.drop_index('idx_org_name', table_name='sam_data')
    op.drop_index('idx_extracted_at', table_name='sam_data')
    op.create_index(op.f('idx_extracted_file'), 'sam_data', ['file_id'], unique=False)
    op.create_index(op.f('idx_extracted_extracted_at'), 'sam_data', ['extracted_at'], unique=False)
    op.drop_column('sam_data', 'website')
    op.drop_column('sam_data', 'fiscal_year_end')
    op.drop_column('sam_data', 'business_start_date')
    op.drop_column('sam_data', 'congressional_district')
    op.drop_column('sam_data', 'country')
    op.drop_column('sam_data', 'zip_extension')
    op.drop_column('sam_data', 'zip_code')
    op.drop_column('sam_data', 'state')
    op.drop_column('sam_data', 'city')
    op.drop_column('sam_data', 'address_line2')
    op.drop_column('sam_data', 'address_line1')
    op.drop_column('sam_data', 'division_name')
    op.drop_column('sam_data', 'legal_business_name')
    op.drop_column('sam_data', 'organization_name')
    op.drop_column('sam_data', 'activation_date')
    op.drop_column('sam_data', 'last_update_date')
    op.drop_column('sam_data', 'expiration_date')
    op.drop_column('sam_data', 'registration_date')
    op.drop_column('sam_data', 'entity_type')
    op.drop_column('sam_data', 'status_code')
    op.drop_column('sam_data', 'duns_number')
    op.drop_column('sam_data', 'record_id')
    op.drop_column('sam_data', 'extracted_type')
    op.drop_index('idx_table_columns_table_name', table_name='table_headers', postgresql_where='is_visible = TRUE')
    op.drop_table('table_headers')
    # ### end Alembic commands ###
