"""inital clean schema

Revision ID: a4aceafc7231
Revises: 
Create Date: 2026-03-24 15:33:06.274202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4aceafc7231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_index('idx_admins_email', 'admins', ['email'], unique=False)
    op.create_index('idx_admins_username', 'admins', ['username'], unique=False)
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('file_version', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_month_year', sa.Integer(), nullable=False),
    sa.Column('processor_type', sa.String(length=10), nullable=False),
    sa.Column('processor_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("processor_type IN ('admin','user')", name='check_processor_type'),
    sa.CheckConstraint('file_month_year BETWEEN 21000 AND 122099', name='check_file_month_year'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_downloads_file', 'files', ['file_id'], unique=False)
    op.create_index('idx_files_month_year', 'files', ['file_month_year'], unique=False)
    op.create_index('idx_files_processor', 'files', ['processor_type', 'processor_id'], unique=False)
    op.create_index('idx_processed_time', 'files', ['processed_at'], unique=False)
    op.create_index('unique_file_name_month_year', 'files', ['file_name', 'file_month_year'], unique=True)
    op.create_table('table_headers',
    sa.Column('table_header_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('column_name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('order', sa.SmallInteger(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('table_header_id'),
    sa.UniqueConstraint('table_name', 'column_name', name='uq_table_column')
    )
    op.create_index('idx_table_columns_table_name', 'table_headers', ['table_name'], unique=False, postgresql_where='is_visible = TRUE')
    op.create_table('sam_data',
    sa.Column('sam_data_id', sa.UUID(), nullable=False),
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('extracted_type', sa.String(length=10), nullable=False),
    sa.Column('extracted_by', sa.UUID(), nullable=False),
    sa.Column('record_id', sa.String(length=50), nullable=False),
    sa.Column('duns_number', sa.String(length=50), nullable=True),
    sa.Column('status_code', sa.String(length=10), nullable=True),
    sa.Column('entity_type', sa.String(length=10), nullable=True),
    sa.Column('registration_date', sa.String(length=20), nullable=True),
    sa.Column('expiration_date', sa.String(length=20), nullable=True),
    sa.Column('last_update_date', sa.String(length=20), nullable=True),
    sa.Column('activation_date', sa.String(length=20), nullable=True),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('legal_business_name', sa.String(length=255), nullable=True),
    sa.Column('division_name', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('zip_code', sa.String(length=20), nullable=True),
    sa.Column('zip_extension', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('congressional_district', sa.String(length=20), nullable=True),
    sa.Column('business_start_date', sa.String(length=20), nullable=True),
    sa.Column('fiscal_year_end', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.CheckConstraint("extracted_type IN('admin', 'user')", name='check_extracted_type'),
    sa.ForeignKeyConstraint(['file_id'], ['files.file_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sam_data_id')
    )
    op.create_index('idx_extracted_at', 'sam_data', ['extracted_at'], unique=False)
    op.create_index('idx_org_name', 'sam_data', ['organization_name'], unique=False)
    op.create_index('idx_sam_data_file', 'sam_data', ['file_id'], unique=False)
    op.create_index('idx_state', 'sam_data', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_state', table_name='sam_data')
    op.drop_index('idx_sam_data_file', table_name='sam_data')
    op.drop_index('idx_org_name', table_name='sam_data')
    op.drop_index('idx_extracted_at', table_name='sam_data')
    op.drop_table('sam_data')
    op.drop_index('idx_table_columns_table_name', table_name='table_headers', postgresql_where='is_visible = TRUE')
    op.drop_table('table_headers')
    op.drop_index('unique_file_name_month_year', table_name='files')
    op.drop_index('idx_processed_time', table_name='files')
    op.drop_index('idx_files_processor', table_name='files')
    op.drop_index('idx_files_month_year', table_name='files')
    op.drop_index('idx_downloads_file', table_name='files')
    op.drop_table('files')
    op.drop_index('idx_admins_username', table_name='admins')
    op.drop_index('idx_admins_email', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
