"""create files table

Revision ID: b88f346ae5fe
Revises: 98bf454f61f6
Create Date: 2026-03-20 16:38:31.695959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b88f346ae5fe'
down_revision: Union[str, Sequence[str], None] = '98bf454f61f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('files',
    sa.Column('file_id', sa.UUID(), nullable=False),
    sa.Column('file_version', sa.String(length=50), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_month_year', sa.Integer(), nullable=False),
    sa.Column('processor_type', sa.String(length=10), nullable=False),
    sa.Column('processor_id', sa.UUID(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint("processor_type IN ('admin','user')", name='check_processor_type'),
    sa.CheckConstraint('file_month_year BETWEEN 21000 AND 122099', name='check_file_month_year'),
    sa.PrimaryKeyConstraint('file_id')
    )
    op.create_index('idx_downloads_file', 'files', ['file_id'], unique=False)
    op.create_index('idx_files_month_year', 'files', ['file_month_year'], unique=False)
    op.create_index('idx_files_processor', 'files', ['processor_type', 'processor_id'], unique=False)
    op.create_index('idx_processed_time', 'files', ['processed_at'], unique=False)
    op.create_index('unique_file_name_month_year', 'files', ['file_name', 'file_month_year'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_file_name_month_year', table_name='files')
    op.drop_index('idx_processed_time', table_name='files')
    op.drop_index('idx_files_processor', table_name='files')
    op.drop_index('idx_files_month_year', table_name='files')
    op.drop_index('idx_downloads_file', table_name='files')
    op.drop_table('files')
    # ### end Alembic commands ###
